### ISSUE TITLE
FeedAHelp: Collect all Ingredient Images and Icons

### ISSUE THREAD

**Issue by TanvirAlam** [FeedAHelp/FeedAHelpless#106]
Related to #102 , #101 

We will need transparent PNG image version of all ingredients

Sample

![Image](https://github.com/FeedAHelp/FeedAHelpless/assets/3250040/81247734-2ac5-4068-970a-6b300e1bf40c)

**Comment by TanvirAlam** [comment]
Keep all the Images in here: https://drive.google.com/drive/folders/18byY-9E4lFtjWzGRyyKArtxTomPYQgkW?usp=sharing

**Comment by MuksanaAkter** [comment]
Link of the excel sheet: https://docs.google.com/spreadsheets/d/1oYA7eE_2IzpT-_iedU5bA2vzIX281GUdxUN4Mbk7uHM/edit#gid=0

**Comment by TanvirAlam** [comment]
@MuksanaAkter Nice work we have #177 now, lets close this
