### ISSUE TITLE
FeedAHelp: Custom Generic Spinner

### ISSUE THREAD

**Issue by TanvirAlam** [FeedAHelp/FeedAHelpless#139]
The Custom Generic Spinner is a user interface (UI) component designed to enhance the user experience of the FeedAHelp web application. The spinner will be used to indicate loading, processing, or waiting states during various interactions within the application.

**Functional Requirements:**

1. Display and Animation:
The spinner should display a visually appealing and engaging animation that indicates activity or loading status to the user.

2. Customizability:
The spinner should be customisable in terms of size, color, and animation style to align with the overall design and branding of the FeedAHelp application.

3. Responsive Design:
The spinner should adapt to different screen sizes and orientations, ensuring a seamless experience across various devices and resolutions.

4. Accessibility:
The spinner should meet accessibility standards, including proper labeling, keyboard navigation, and compatibility with screen readers for users with disabilities.

5. Dynamic Loading States:
The spinner should dynamically appear and disappear based on the application's loading or processing states, triggered by asynchronous actions such as data retrieval or submission.

**Comment by TanvirAlam** [comment]
@RoksanaMou Please help to select the best one that matches with feedAHelp

**Comment by RoksanaMou** [comment]
According to primary color:

https://uiverse.io/S4tyendra/fast-frog-87

https://uiverse.io/JaydipPrajapati1910/white-newt-56

https://uiverse.io/Shoh2008/perfect-fireant-0

**Comment by TanvirAlam** [comment]
We have chosen:
Source code: https://uiverse.io/S4tyendra/fast-frog-87


![Image](https://github.com/FeedAHelp/FeedAHelpless/assets/3250040/b3729ea3-696a-4994-bdd4-58fcce6075e9)
