### ISSUE TITLE
FeedAHelp: Make top navigation great again

### ISSUE THREAD

**Issue by TanvirAlam** [FeedAHelp/FeedAHelpless#169]
Current One;

![Image](https://github.com/FeedAHelp/FeedAHelpless/assets/3250040/a9201ca0-2e12-456a-a0bc-94e35f09d23a)

NEW DESIGN
![Image](https://github.com/FeedAHelp/FeedAHelpless/assets/3250040/a94aacd7-94a2-4bb1-9d93-22b95bb45cdd)

**Comment by TanvirAlam** [comment]
1. Make logo smaller and clickable redirect to `/` root
2. Keep avatar the same as it is make it small
3. change the language Icon
4. Add a Currency drop down

**Comment by TanvirAlam** [comment]
Currency Icon
![Image](https://github.com/FeedAHelp/FeedAHelpless/assets/3250040/680cf184-aa1e-413e-963e-baee539d8e90)

Language Icon
![Image](https://github.com/FeedAHelp/FeedAHelpless/assets/3250040/a5a553a4-d12b-42a5-8dbd-436f0aed3e9f)
or


![Image](https://github.com/FeedAHelp/FeedAHelpless/assets/3250040/c8e7cd5e-cc69-44a0-a956-715474538361)



![Image](https://github.com/FeedAHelp/FeedAHelpless/assets/3250040/30e0e7c0-6fda-41b8-9598-b4bfa1ecafef)

**Comment by Rakibs511** [comment]
Result

![Image](https://github.com/FeedAHelp/FeedAHelpless/assets/108168071/72a5a9c1-e977-4fb9-bd7e-eebd7467308d)

**Comment by TanvirAlam** [comment]
![Image](https://github.com/FeedAHelp/FeedAHelpless/assets/3250040/c28edc06-7d14-45ad-88ef-ab449606c563)

1. remove the ash color background
2. bring the arroy closer to the icon

**Comment by Rakibs511** [comment]
**Added hover and onClick effect and removed bg**

![Image](https://github.com/FeedAHelp/FeedAHelpless/assets/108168071/65f1de86-6336-4136-9b8f-78d43d2bd367)
