### ISSUE TITLE
BUGS: Fix the navigation blurness when scrolling

### ISSUE THREAD

**Issue by TanvirAlam** [FeedAHelp/FeedAHelpless#195]
![Image](https://github.com/FeedAHelp/FeedAHelpless/assets/3250040/1969776b-615a-4cab-a4c1-1b7938f119db)

**Comment by TanvirAlam** [comment]
Problem: Previously when scrolling the top navigation was blur, now its not

Solution: Bring it back, go back to the code and bring back the code that has been deleted. its CSS code

**Comment by Rakibs511** [comment]
### before scroll

![Image](https://github.com/FeedAHelp/FeedAHelpless/assets/108168071/6ce3af7f-a430-4a8c-867c-4ea1dc387898)

### after scroll

![Image](https://github.com/FeedAHelp/FeedAHelpless/assets/108168071/1e879b95-5938-4969-8b7f-dd6110b4a834)
