### ISSUE TITLE
BUGS: When in mobile add currency and language right hand side bar in Burger menu

### ISSUE THREAD

**Issue by TanvirAlam** [FeedAHelp/FeedAHelpless#200]
Problem:

![Image](https://github.com/FeedAHelp/FeedAHelpless/assets/3250040/cdee7cd6-9724-4b4a-80a6-6d2fe07fdbef)

**Comment by TanvirAlam** [comment]
Solution: https://codepen.io/kelvinqueiroz/pen/GBJYbd


![Image](https://github.com/FeedAHelp/FeedAHelpless/assets/3250040/a24e6e80-0ee3-4fd2-bd4c-abf54a522e08)

**Comment by Rakibs511** [comment]
### Result

![Image](https://github.com/FeedAHelp/FeedAHelpless/assets/108168071/6b26072d-5cfc-4fb2-b877-276c9f3e72ab)
