### ISSUE TITLE
BUGS: Make social icon black and on hover original color

### ISSUE THREAD

**Issue by TanvirAlam** [FeedAHelp/FeedAHelpless#220]
![Image](https://github.com/FeedAHelp/FeedAHelpless/assets/3250040/eba589db-840f-4517-9abf-5446b9bc4dc3)

**Comment by TanvirAlam** [comment]
![Image](https://github.com/FeedAHelp/FeedAHelpless/assets/3250040/0783785b-5bc0-48f9-8cc8-10c59a07ba67)

Source code: https://codepen.io/ben1099user/details/rNMOMpK

- Initial state: Icon is black
- when hover: it scales and change color

**Comment by Rakibs511** [comment]
### Result 

![Image](https://github.com/FeedAHelp/FeedAHelpless/assets/108168071/f48513e6-3577-4286-a7e9-c569432d4871)
