### ISSUE TITLE
FeedAHelp: Define 3 different color types

### ISSUE THREAD

**Issue by TanvirAlam** [FeedAHelp/FeedAHelpless#259]
Colors can be categorized into various types based on different criteria. Here are some of the primary types of colors:

**Primary Colors:** These are the fundamental colors that cannot be created by mixing other colors. In traditional color theory, the primary colors are red, blue, and yellow. They are used as the basis for creating all other colors.

**Secondary Colors:** Secondary colors are created by mixing equal parts of two primary colors. The three secondary colors are green (from blue and yellow), orange (from red and yellow), and purple (from red and blue).

**Tertiary Colors:** Tertiary colors are formed by mixing a primary color with a neighboring secondary color. Examples include red-orange, yellow-green, and blue-purple. Tertiary colors are positioned between a primary and a secondary color on the color wheel.

These categories provide a framework for understanding and working with colors in various artistic and design contexts. Depending on the field and purpose, different color types and combinations may be preferred to achieve specific visual effects and convey intended messages.

**Comment by TanvirAlam** [comment]
**Primary colors,** which typically include red, blue, and yellow in traditional color theory, can be used effectively in various ways on websites to achieve specific design goals and create visually appealing and user-friendly interfaces. Here are some examples of where primary colors can be used on websites:

- Brand Identity: Primary colors are often a foundational element of a website's brand identity. They can be used in the logo, header, and other prominent areas to reinforce the brand's visual identity and recognition.
- Navigation Elements: Primary colors can be used for navigation elements such as menus, buttons, and links. For example, primary colors can be used for buttons that are meant to stand out and encourage user interaction, like "Sign Up" or "Shop Now" buttons.
- Call-to-Action (CTA) Buttons: Red and blue, being primary colors, can be used for CTA buttons to draw attention and encourage users to take specific actions, such as making a purchase or signing up for a newsletter.
- Highlighting Important Information: Primary colors can be used to highlight important information or key messages on a website. For example, using red for error messages or important alerts can make them more noticeable.
- Visual Hierarchy: Primary colors can help establish a visual hierarchy on a webpage. For instance, you can use primary colors for headings and subheadings to differentiate content and guide users through the page.
- Backgrounds: While primary colors are often used for elements that need to stand out, they can also be used as background colors for sections of a website. Careful use of primary colors as backgrounds can create a cohesive and visually appealing design.
- Interactive Elements: Interactive elements like sliders, progress bars, and form elements can be styled using primary colors to make them visually engaging and user-friendly.
- Category Labels: If your website features categories or sections, primary colors can be used to color-code or label these categories, making it easier for users to navigate and find relevant content.
- Icons and Illustrations: Primary colors can be used in icons and illustrations to create a consistent and visually appealing design language throughout the website.
- Accessibility: When using primary colors, it's essential to consider accessibility. Ensure that text on primary color backgrounds maintains sufficient contrast for readability, and follow accessibility guidelines to make your website usable for everyone, including those with visual impairments.


**Secondary colors,** which are created by mixing two primary colors, can be effectively used in various ways on websites to complement primary colors and create a visually appealing and harmonious design. Here are some examples of where secondary colors can be used on websites:

- Accents and Highlights: Secondary colors can be used as accent colors to draw attention to specific elements on a webpage. For example, you can use secondary colors for hover effects on buttons or links to indicate interactivity.
- Section Dividers: Secondary colors can be used as section dividers or background highlights to visually separate different content sections on a webpage. This can help users navigate and understand the page structure.
- Icons and Graphics: Secondary colors can be used for icons, illustrations, and graphics to add depth and visual interest to your website's design. They can make visual elements stand out and reinforce the overall design theme.
- Secondary Buttons: In addition to primary call-to-action (CTA) buttons, you can use secondary colors for less prominent buttons, such as "Learn More" or "Read More" buttons, to provide additional options without overwhelming the user.
- Forms and Input Fields: Secondary colors can be applied to form elements, such as input fields, checkboxes, and radio buttons, to make them visually distinct and user-friendly.
- Progress Indicators: Secondary colors can be used for progress bars or indicators, helping users track their progress on tasks or forms.
- Typography: Secondary colors can be applied to text elements, such as headings, subheadings, or quotes, to create a hierarchy of information and add visual interest to the typography.
- Background Elements: Secondary colors can be used for background elements, such as sidebars, tooltips, or modals, to provide additional context or information without distracting from the main content.
- Notification and Feedback Messages: Use secondary colors to differentiate notification messages, such as success messages (green), warning messages (yellow), and error messages (red), to convey different types of feedback to users.
- Secondary Navigation: If your website has secondary navigation menus or submenus, you can use secondary colors to distinguish them from the primary navigation and help users navigate efficiently.

Tertiary colors, which are created by mixing a primary color with a neighboring secondary color, can add depth and complexity to your website's color palette. Here are some ways you can use tertiary colors in web design:

- Subtle Gradients: Tertiary colors can be used to create subtle gradients or color transitions in backgrounds, headers, or other design elements. This can add visual interest and depth to your website's design.
- Highlighting Key Elements: Use tertiary colors to highlight key elements on your website, such as buttons, icons, or headings. This can draw attention to important information or calls to action.
- Borders and Dividers: Tertiary colors can be applied to borders and dividers between sections of content. This can help visually separate content and create a clear page structure.
- Icons and Graphics: Tertiary colors can be used in icons, illustrations, and graphics to introduce additional hues into your visual language. This can make your website more visually engaging and unique.
- Typography: Apply tertiary colors to typography elements, such as drop caps, pull quotes, or decorative text. This can add flair and style to your website's text content.
- Buttons and Links: Consider using tertiary colors for less prominent buttons or links to provide additional options or to differentiate them from primary and secondary actions.
- Background Accents: Tertiary colors can be used as subtle background accents in specific sections of your website, adding a touch of color without overwhelming the overall design.
- Interactive Elements: Apply tertiary colors to interactive elements like sliders, progress bars, or tooltips to make them visually appealing and user-friendly.
- Thematic Elements: If your website has a specific theme or concept, use tertiary colors to reinforce that theme and create a cohesive visual experience for users.
- Forms and Input Fields: Tertiary colors can be used for form elements, such as input field borders or checkboxes, to make them visually distinguishable and user-friendly.

**Comment by TanvirAlam** [comment]
@MuksanaAkter We need 5 colors on each

- Primary Color: 5 colors
- Secoundery color: 5 colors
- Tertiary colors: can be unlimited (just do 5 for now)

**Comment by MuksanaAkter** [comment]
primary: {
    deep_orange: "#f6580b",
    red: "#e92525",
    gold: "#ffd700",
    navy_Blue: #001F3F,
    white: #ffff,
    deep_green: #008000;

  }
  secondary: {
    Dark Teal:"#1A535C",
    Aquamarine:"#2A9D8F",
    medium_gray: #cccccc
    Terra_Cotta: #E2725B,
    medium_dark_green: "#327832",
    medium_blue: #0466C8;
    light_yellow: "#ffff00",
    Lime_Green: #32CD32,
    Bright_Cyan: #00FFFF,
    black: #111;
  }
  tertiary: {
    lightYellow: "#fff2b6",
    lightOrange:" #fed8b1",
    lightRed: "#fbc3bc",
    lightBlue: "#b8e2f2",
    lightTeal: "#b8edeb",
    lightGreen: "#caffda",

  }

**Comment by TanvirAlam** [comment]
closing this #298
