### ISSUE TITLE
BUGS: Add custome scrollbar for ingredients and Deshi menu

### ISSUE THREAD

**Issue by TanvirAlam** [FeedAHelp/FeedAHelpless#264]
![Image](https://github.com/FeedAHelp/FeedAHelpless/assets/3250040/6ab89f6f-6edd-4a42-850f-d7f9c5d11e3d)

**Comment by Rakibs511** [comment]
### result

![Image](https://github.com/FeedAHelp/FeedAHelpless/assets/108168071/476cd022-0de0-4090-9f4e-a5c946a43339)
