### ISSUE TITLE
BUGS: Fix Google rechaptach

### ISSUE THREAD

**Issue by TanvirAlam** [FeedAHelp/FeedAHelpless#276]
![Image](https://github.com/FeedAHelp/FeedAHelpless/assets/3250040/e57082ec-c919-4d50-ae73-3b21175ba127)

**Comment by Rakibs511** [comment]
### result
https://github.com/FeedAHelp/FeedAHelpless/assets/108168071/ee87006d-8633-47f8-a54c-e17c39599043
