### ISSUE TITLE
BUGS: FeedAHelp Hero logo padding issue

### ISSUE THREAD

**Issue by TanvirAlam** [FeedAHelp/FeedAHelpless#374]
![Image](https://github.com/FeedAHelp/FeedAHelpless/assets/3250040/4705dde9-4023-41c0-8223-3d86cb356863)

**Comment by sojib-mondol** [comment]
![Image](https://github.com/FeedAHelp/FeedAHelpless/assets/57976126/84921855-9487-4562-8163-da7d0b6c328d)

**Comment by sojib-mondol** [comment]
![Image](https://github.com/FeedAHelp/FeedAHelpless/assets/57976126/fe339fd6-1828-46c1-8394-fb2ca193dd9e)
